insert into product(product_no, product_name, product_price, product_category, product_qty, product_image, product_star_avg, product_pet_category, product_detail_image) values(product_product_no_SEQ.nextval, '우프니 독 크런치 밀크 210g', 7200, '간식', 0, 'woofny_dog_crunch_milk.jpg', 5, '강아지', 'woofny_dog_crunch_detail.jpg');
insert into product(product_no, product_name, product_price, product_category, product_qty, product_image, product_star_avg, product_pet_category, product_detail_image) values(product_product_no_SEQ.nextval, '우프니 독 크런치 고구마 210g', 7200, '간식', 0, 'woofny_dog_crunch_sweetpotato.jpg', 3, '강아지', 'woofny_dog_crunch_detail.jpg');
insert into product(product_no, product_name, product_price, product_category, product_qty, product_image, product_star_avg, product_pet_category, product_detail_image) values(product_product_no_SEQ.nextval, '우프니 독 크런치 BBQ 210g', 7200, '간식', 0, 'woofny_dog_crunch_bbq.jpg', 3, '강아지', 'woofny_dog_crunch_detail.jpg');
insert into product(product_no, product_name, product_price, product_category, product_qty, product_image, product_star_avg, product_pet_category, product_detail_image) values(product_product_no_SEQ.nextval, '우프니 플라워츄 마리골드 150g', 4500, '간식', 0, 'woofny_flowerchew_marigold.jpg', 3, '강아지', 'woofny_flowerchew_marigold_detail.jpg');
insert into product(product_no, product_name, product_price, product_category, product_qty, product_image, product_star_avg, product_pet_category, product_detail_image) values(product_product_no_SEQ.nextval, '우프니 플라워츄 캐모마일 150g', 4500, '간식', 0, 'woofny_flowerchew_chamomile.jpg', 3, '강아지', 'woofny_flowerchew_marigold_detail.jpg');
insert into product(product_no, product_name, product_price, product_category, product_qty, product_image, product_star_avg, product_pet_category, product_detail_image) values(product_product_no_SEQ.nextval, '우프니 플라워츄 스피루리나 150g', 4500, '간식', 0, 'woofny_flowerchew_spirulina.jpg', 3, '강아지', 'woofny_flowerchew_marigold_detail.jpg');
insert into product(product_no, product_name, product_price, product_category, product_qty, product_image, product_star_avg, product_pet_category, product_detail_image) values(product_product_no_SEQ.nextval, '우프니 플라워츄 밀크씨슬 150g', 4500, '간식', 0, 'woofny_flowerchew_milkthistle.jpg', 3, '강아지', 'woofny_flowerchew_marigold_detail.jpg');

insert into product(product_no, product_name, product_price, product_category, product_qty, product_image, product_star_avg, product_pet_category, product_detail_image) values(product_product_no_SEQ.nextval, '뽀시래기 강아지 치석제거 플라그츄 덴탈껌 관절건강 6개입', 11000, '간식', 0, 'bbosiraegi_plaque_chew_joint.jpg', 3, '강아지', 'bbosiraegi_plaque_chew_detail.jpg');
insert into product(product_no, product_name, product_price, product_category, product_qty, product_image, product_star_avg, product_pet_category, product_detail_image) values(product_product_no_SEQ.nextval, '뽀시래기 강아지 치석제거 플라그츄 덴탈껌 장건강 6개입', 11000, '간식', 0, 'bbosiraegi_plaque_chew_gut.jpg', 2, '강아지', 'bbosiraegi_plaque_chew_detail.jpg');
insert into product(product_no, product_name, product_price, product_category, product_qty, product_image, product_star_avg, product_pet_category, product_detail_image) values(product_product_no_SEQ.nextval, '뽀시래기 강아지 치석제거 플라그츄 덴탈껌 눈겅간 6개입', 11000, '간식', 0, 'bbosiraegi_plaque_chew_eyes.jpg', 4, '강아지', 'bbosiraegi_plaque_chew_detail.jpg');
insert into product(product_no, product_name, product_price, product_category, product_qty, product_image, product_star_avg, product_pet_category, product_detail_image) values(product_product_no_SEQ.nextval, '뽀시래기 강아지 동결건조 치킨 트릿 120g', 15000, '간식', 0, 'bbosiraegi_lyophilization_chicken.jpg', 4, '강아지', 'bbosiraegi_lyophilization_detail.jpg');
insert into product(product_no, product_name, product_price, product_category, product_qty, product_image, product_star_avg, product_pet_category, product_detail_image) values(product_product_no_SEQ.nextval, '뽀시래기 강아지 동결건조 북어 트릿 120g', 15000, '간식', 0, 'bbosiraegi_lyophilization_driedpollack.jpg', 4, '강아지', 'bbosiraegi_lyophilization_detail.jpg');

insert into product(product_no, product_name, product_price, product_category, product_qty, product_image, product_star_avg, product_pet_category, product_detail_image) values(product_product_no_SEQ.nextval, '이마시아 소고기 소세지 8p', 1500, '간식', 0, 'emasia_sausage_beef.jpg', 3, '강아지', 'emasia_sausage_detail.jpg');
insert into product(product_no, product_name, product_price, product_category, product_qty, product_image, product_star_avg, product_pet_category, product_detail_image) values(product_product_no_SEQ.nextval, '이마시아 양고기 소세지 8p', 1500, '간식', 0, 'emasia_sausage_lamb.jpg', 5, '강아지', 'emasia_sausage_detail.jpg');
insert into product(product_no, product_name, product_price, product_category, product_qty, product_image, product_star_avg, product_pet_category, product_detail_image) values(product_product_no_SEQ.nextval, '이마시아 닭고기 소세지 8p', 1500, '간식', 0, 'emasia_sausage_chicken.jpg', 4, '강아지', 'emasia_sausage_detail.jpg');
insert into product(product_no, product_name, product_price, product_category, product_qty, product_image, product_star_avg, product_pet_category, product_detail_image) values(product_product_no_SEQ.nextval, '이마시아 오리고기 소세지 8p', 1500, '간식', 0, 'emasia_sausage_duck.jpg', 4, '강아지', 'emasia_sausage_detail.jpg');

insert into product(product_no, product_name, product_price, product_category, product_qty, product_image, product_star_avg, product_pet_category, product_detail_image) values(product_product_no_SEQ.nextval, '닥터할리 펫 밀크 바닐라 200ml', 1600, '간식', 0, 'dr.holi_petmilk_vanilla.jpg', 3, '강아지', 'dr.holi_petmilk_detail.jpg');
insert into product(product_no, product_name, product_price, product_category, product_qty, product_image, product_star_avg, product_pet_category, product_detail_image) values(product_product_no_SEQ.nextval, '닥터할리 펫 밀크 베이비 200ml', 1600, '간식', 0, 'dr.holi_petmilk_baby.jpg', 5, '강아지', 'dr.holi_petmilk_detail.jpg');
insert into product(product_no, product_name, product_price, product_category, product_qty, product_image, product_star_avg, product_pet_category, product_detail_image) values(product_product_no_SEQ.nextval, '닥터할리 펫 밀크 어덜트 200ml', 1600, '간식', 0, 'dr.holi_petmilk_adult.jpg', 5, '강아지', 'dr.holi_petmilk_detail.jpg');
insert into product(product_no, product_name, product_price, product_category, product_qty, product_image, product_star_avg, product_pet_category, product_detail_image) values(product_product_no_SEQ.nextval, '닥터할리 펫 밀크 시니어 200ml', 1600, '간식', 0, 'dr.holi_petmilk_senior.jpg', 1, '강아지', 'dr.holi_petmilk_detail.jpg');

insert into product(product_no, product_name, product_price, product_category, product_qty, product_image, product_star_avg, product_pet_category, product_detail_image) values(product_product_no_SEQ.nextval, '아임펫 리얼 통살의 정석 참치맛 10개입', 5000, '간식', 0, 'impet_tuna.jpg', 4, '강아지', 'impet_detail.jpg');
insert into product(product_no, product_name, product_price, product_category, product_qty, product_image, product_star_avg, product_pet_category, product_detail_image) values(product_product_no_SEQ.nextval, '아임펫 리얼 통살의 정석 황태맛 10개입', 5000, '간식', 0, 'impet_dried pollack.jpg', 5, '강아지', 'impet_detail.jpg');
insert into product(product_no, product_name, product_price, product_category, product_qty, product_image, product_star_avg, product_pet_category, product_detail_image) values(product_product_no_SEQ.nextval, '아임펫 리얼 통살의 정석 연어맛 10개입', 5000, '간식', 0, 'impet_salmon.jpg', 1, '강아지', 'impet_detail.jpg');
insert into product(product_no, product_name, product_price, product_category, product_qty, product_image, product_star_avg, product_pet_category, product_detail_image) values(product_product_no_SEQ.nextval, '아임펫 부드러운 소프트볼 북어 120g', 5500, '간식', 0, 'impet_softball_salmon.jpg', 1, '강아지', 'impet_softball_detail.jpg');
insert into product(product_no, product_name, product_price, product_category, product_qty, product_image, product_star_avg, product_pet_category, product_detail_image) values(product_product_no_SEQ.nextval, '아임펫 부드러운 소프트볼 연어 120g', 5500, '간식', 0, 'impet_softball_driedpollack.jpg', 1, '강아지', 'impet_softball_detail.jpg');

insert into product(product_no, product_name, product_price, product_category, product_qty, product_image, product_star_avg, product_pet_category, product_detail_image) values(product_product_no_SEQ.nextval, '스위피 오독오독 바삭 시금치 120g', 15900, '간식', 0, 'swiffy_spinach.jpg', 5, '강아지', 'swiffy_detail.jpg');
insert into product(product_no, product_name, product_price, product_category, product_qty, product_image, product_star_avg, product_pet_category, product_detail_image) values(product_product_no_SEQ.nextval, '스위피 오독오독 바삭 당근 120g', 15900, '간식', 0, 'swiffy_carrot.jpeg', 4, '강아지', 'swiffy_detail.jpg');
insert into product(product_no, product_name, product_price, product_category, product_qty, product_image, product_star_avg, product_pet_category, product_detail_image) values(product_product_no_SEQ.nextval, '스위피 오독오독 바삭 고구마 120g', 15900, '간식', 0, 'swiffy_sweetpotato.jpeg', 4, '강아지', 'swiffy_detail.jpg');
insert into product(product_no, product_name, product_price, product_category, product_qty, product_image, product_star_avg, product_pet_category, product_detail_image) values(product_product_no_SEQ.nextval, '스위피 오독오독 바삭 연어껍질 120g', 15900, '간식', 0, 'swiffy_salmon.jpeg', 3, '강아지', 'swiffy_detail.jpg');
insert into product(product_no, product_name, product_price, product_category, product_qty, product_image, product_star_avg, product_pet_category, product_detail_image) values(product_product_no_SEQ.nextval, '스위피 오독오독 바삭 덕브로콜리 120g', 15900, '간식', 0, 'swiffy_broccoli.jpg', 1, '강아지', 'swiffy_detail.jpg');
insert into product(product_no, product_name, product_price, product_category, product_qty, product_image, product_star_avg, product_pet_category, product_detail_image) values(product_product_no_SEQ.nextval, '스위피 오독오독 바삭 치킨블루베리 120g', 15900, '간식', 0, 'swiffy_chicken_blueberry.jpeg', 2, '강아지', 'swiffy_detail.jpg');

insert into product(product_no, product_name, product_price, product_category, product_qty, product_image, product_star_avg, product_pet_category, product_detail_image) values(product_product_no_SEQ.nextval, '네츄럴코어 강아지캔 치킨 야채 95g', 1600, '캔', 0, 'naturalcore_chicken_vegetable.jpg', 5, '강아지', 'naturalcore_detail.jpg');
insert into product(product_no, product_name, product_price, product_category, product_qty, product_image, product_star_avg, product_pet_category, product_detail_image) values(product_product_no_SEQ.nextval, '네츄럴코어 강아지캔 게맛살 치킨 95g', 1600, '캔', 0, 'naturalcore_crab_chicken.jpg', 5, '강아지', 'naturalcore_detail.jpg');
insert into product(product_no, product_name, product_price, product_category, product_qty, product_image, product_star_avg, product_pet_category, product_detail_image) values(product_product_no_SEQ.nextval, '네츄럴코어 강아지캔 치킨 라이스 95g', 1600, '캔', 0, 'naturalcore_chicken_rice.jpg', 5, '강아지', 'naturalcore_detail.jpg');
insert into product(product_no, product_name, product_price, product_category, product_qty, product_image, product_star_avg, product_pet_category, product_detail_image) values(product_product_no_SEQ.nextval, '네츄럴코어 강아지캔 치킨 95g', 1600, '캔', 0, 'naturalcore_chicken.jpg', 5, '강아지', 'naturalcore_detail.jpg');

insert into product(product_no, product_name, product_price, product_category, product_qty, product_image, product_star_avg, product_pet_category, product_detail_image) values(product_product_no_SEQ.nextval, '럭셔리독 소고기 캔 100g', 900, '캔', 0, 'luxurydog_beef.jpg', 4, '강아지', 'luxurydog_detail.jpg');
insert into product(product_no, product_name, product_price, product_category, product_qty, product_image, product_star_avg, product_pet_category, product_detail_image) values(product_product_no_SEQ.nextval, '럭셔리독 소고기 닭고기 캔 100g', 900, '캔', 0, 'luxurydog_beef_chicken.jpg', 2, '강아지', 'luxurydog_detail.jpg');
insert into product(product_no, product_name, product_price, product_category, product_qty, product_image, product_star_avg, product_pet_category, product_detail_image) values(product_product_no_SEQ.nextval, '럭셔리독 닭고기 캔 100g', 900, '캔', 0, 'luxurydog_chicken.jpg', 3, '강아지', 'luxurydog_detail.jpg');
insert into product(product_no, product_name, product_price, product_category, product_qty, product_image, product_star_avg, product_pet_category, product_detail_image) values(product_product_no_SEQ.nextval, '럭셔리독 소고기 치즈 캔 100g', 900, '캔', 0, 'luxurydog_beef_cheese.jpg', 1, '강아지', 'luxurydog_detail.jpg');
insert into product(product_no, product_name, product_price, product_category, product_qty, product_image, product_star_avg, product_pet_category, product_detail_image) values(product_product_no_SEQ.nextval, '럭셔리독 양고기 캔 100g', 900, '캔', 0, 'luxurydog_lamb.jpg', 2, '강아지', '');

insert into product(product_no, product_name, product_price, product_category, product_qty, product_image, product_star_avg, product_pet_category, product_detail_image) values(product_product_no_SEQ.nextval, '지위픽 독 에어드라이 소고기 454g', 49000, '사료', 0, 'ziwipeak_beef.jpg', 4, '강아지', 'ziwipeak_detail.jpg');
insert into product(product_no, product_name, product_price, product_category, product_qty, product_image, product_star_avg, product_pet_category, product_detail_image) values(product_product_no_SEQ.nextval, '지위픽 독 에어드라이 사슴고기 454g', 70000, '사료', 0, 'ziwipeak_venison.jpg', 5, '강아지', 'ziwipeak_detail.jpg');
insert into product(product_no, product_name, product_price, product_category, product_qty, product_image, product_star_avg, product_pet_category, product_detail_image) values(product_product_no_SEQ.nextval, '지위픽 독 에어드라이 트라이프 양고기 454g', 49000, '사료', 0, 'ziwipeak_tripe_lamb.jpg', 1, '강아지', 'ziwipeak_detail.jpg');
insert into product(product_no, product_name, product_price, product_category, product_qty, product_image, product_star_avg, product_pet_category, product_detail_image) values(product_product_no_SEQ.nextval, '지위픽 독 에어드라이 양고기 454g', 49000, '사료', 0, 'ziwipeak_lamb.jpg', 1, '강아지', 'ziwipeak_detail.jpg');
insert into product(product_no, product_name, product_price, product_category, product_qty, product_image, product_star_avg, product_pet_category, product_detail_image) values(product_product_no_SEQ.nextval, '지위픽 독 에어드라이 고등어 양고기 454g', 54000, '사료', 0, 'ziwipeak_mackerel_lamb.jpg', 1, '강아지', 'ziwipeak_detail.jpg');
insert into product(product_no, product_name, product_price, product_category, product_qty, product_image, product_star_avg, product_pet_category, product_detail_image) values(product_product_no_SEQ.nextval, '지위픽 독 에어드라이 닭고기 454g', 48000, '사료', 0, 'ziwipeak_chicken.jpg', 1, '강아지', 'ziwipeak_detail.jpg');

insert into product(product_no, product_name, product_price, product_category, product_qty, product_image, product_star_avg, product_pet_category, product_detail_image) values(product_product_no_SEQ.nextval, '바른 울트라패드 소형 50매 화이트(40x50cm)', 11000, '위생', 0, 'baruen_ultrapad_white.jpg', 1, '강아지', 'baruen_ultrapad_detail.jpg');
insert into product(product_no, product_name, product_price, product_category, product_qty, product_image, product_star_avg, product_pet_category, product_detail_image) values(product_product_no_SEQ.nextval, '바른 울트라패드 소형 50매 차콜(40x50cm)', 11000, '위생', 0, 'baruen_ultrapad_charcoal.jpg', 4, '강아지', 'baruen_ultrapad_detail.jpg');
insert into product(product_no, product_name, product_price, product_category, product_qty, product_image, product_star_avg, product_pet_category, product_detail_image) values(product_product_no_SEQ.nextval, '바른 울트라패드 대형 20매 화이트(60x75cm)', 12000, '위생', 0, 'baruen_ultrapad_white.jpg', 2, '강아지', 'baruen_ultrapad_detail.jpg');
insert into product(product_no, product_name, product_price, product_category, product_qty, product_image, product_star_avg, product_pet_category, product_detail_image) values(product_product_no_SEQ.nextval, '바른 울트라패드 대형 20매 차콜(60x75cm)', 12000, '위생', 0, 'baruen_ultrapad_charcoal.jpg', 3, '강아지', 'baruen_ultrapad_detail.jpg');

insert into product(product_no, product_name, product_price, product_category, product_qty, product_image, product_star_avg, product_pet_category, product_detail_image) values(product_product_no_SEQ.nextval, '멍냥이랑 올인원패드 가성비타입 초대형 80매', 28900, '위생', 0, 'allinonepad.jpg', 2, '강아지', 'allinonepad_detail.jpg');
insert into product(product_no, product_name, product_price, product_category, product_qty, product_image, product_star_avg, product_pet_category, product_detail_image) values(product_product_no_SEQ.nextval, '멍냥이랑 올인원패드 가성비타입 대형 160매', 28900, '위생', 0, 'allinonepad.jpg', 3, '강아지', 'allinonepad_detail.jpg');
insert into product(product_no, product_name, product_price, product_category, product_qty, product_image, product_star_avg, product_pet_category, product_detail_image) values(product_product_no_SEQ.nextval, '멍냥이랑 올인원패드 가성비타입 중형 200매', 28900, '위생', 0, 'allinonepad.jpg', 5, '강아지', 'allinonepad_detail.jpg');
insert into product(product_no, product_name, product_price, product_category, product_qty, product_image, product_star_avg, product_pet_category, product_detail_image) values(product_product_no_SEQ.nextval, '멍냥이랑 올인원패드 가성비타입 소형 400매', 28900, '위생', 0, 'allinonepad.jpg', 5, '강아지', 'allinonepad_detail.jpg');

insert into product(product_no, product_name, product_price, product_category, product_qty, product_image, product_star_avg, product_pet_category, product_detail_image) values(product_product_no_SEQ.nextval, '에티펫 치아 깨끗 티슈 30매', 2200, '위생', 0, 'etipet_tooth_tissue.jpg', 4, '강아지', 'etipet_tooth_tissue_detail.jpg');
insert into product(product_no, product_name, product_price, product_category, product_qty, product_image, product_star_avg, product_pet_category, product_detail_image) values(product_product_no_SEQ.nextval, '에티펫 눈물자국 깨끗 티슈 30매', 2200, '위생', 0, 'etipet_tear_tissue.jpg', 2, '강아지', 'etipet_tear_tissue_detail.jpeg');
insert into product(product_no, product_name, product_price, product_category, product_qty, product_image, product_star_avg, product_pet_category, product_detail_image) values(product_product_no_SEQ.nextval, '에티펫 귀 깨끗 티슈 30매', 2200, '위생', 0, 'etipet_ear_tissue.jpg', 2, '강아지', 'etipet_ear_tissue_detail.jpeg');
insert into product(product_no, product_name, product_price, product_category, product_qty, product_image, product_star_avg, product_pet_category, product_detail_image) values(product_product_no_SEQ.nextval, '에티펫 버블목욕 시트 15매', 3300, '위생', 0, 'etipet_bubble_shower_tissue.jpg', 2, '강아지', 'etipet_bubble_shower_detail.jpeg');

insert into product(product_no, product_name, product_price, product_category, product_qty, product_image, product_star_avg, product_pet_category, product_detail_image) values(product_product_no_SEQ.nextval, '바잇미 웁스백 생분해 배변봉투 15매x8롤', 9900, '위생', 0, 'biteme_ddong.jpg', 5, '강아지', 'biteme_ddong_detail.jpg');
insert into product(product_no, product_name, product_price, product_category, product_qty, product_image, product_star_avg, product_pet_category, product_detail_image) values(product_product_no_SEQ.nextval, '바잇미 뉴 헤잇미 스프레이', 13900, '위생', 0, 'biteme_hateme_spray.jpg', 5, '강아지', 'biteme_hateme_spray_detail.jpg');
insert into product(product_no, product_name, product_price, product_category, product_qty, product_image, product_star_avg, product_pet_category, product_detail_image) values(product_product_no_SEQ.nextval, '바잇미 미끄럼방지 멀티 목욕매트', 20000, '위생', 0, 'biteme_multimat.jpg', 5, '강아지', 'biteme_multimat_detail.jpg');
insert into product(product_no, product_name, product_price, product_category, product_qty, product_image, product_star_avg, product_pet_category, product_detail_image) values(product_product_no_SEQ.nextval, '바잇미 더블버블 다목적 세제 500ml', 16900, '위생', 0, 'biteme_double_bubble.jpg', 5, '강아지', 'biteme_double_bubble_detail.jpg');

insert into product(product_no, product_name, product_price, product_category, product_qty, product_image, product_star_avg, product_pet_category, product_detail_image) values(product_product_no_SEQ.nextval, '동구밭 반려시선 발비누 시어버터', 13000, '미용', 0, 'donggubat_soap.jpg', 5, '강아지', 'donggubat_soap_detail.jpg');
insert into product(product_no, product_name, product_price, product_category, product_qty, product_image, product_star_avg, product_pet_category, product_detail_image) values(product_product_no_SEQ.nextval, '동구밭 반려시선 강아지 비누', 12000, '미용', 0, 'donggubat_dog_soap.jpg', 5, '강아지', 'donggubat_dog_soap_detail.jpg');
insert into product(product_no, product_name, product_price, product_category, product_qty, product_image, product_star_avg, product_pet_category, product_detail_image) values(product_product_no_SEQ.nextval, '동구밭 반려시선 강아지 샴푸바', 18000, '미용', 0, 'donggubat_shampoo.jpg', 5, '강아지', 'donggubat_shampoo_detail.jpg');
insert into product(product_no, product_name, product_price, product_category, product_qty, product_image, product_star_avg, product_pet_category, product_detail_image) values(product_product_no_SEQ.nextval, '동구밭 반려시선 카밍크림', 32000, '미용', 0, 'donggubat_camingcream.jpg', 5, '강아지', 'donggubat_camingcream_detail.jpg');

insert into product(product_no, product_name, product_price, product_category, product_qty, product_image, product_star_avg, product_pet_category, product_detail_image) values(product_product_no_SEQ.nextval, '도기맨 허니스마일 안면빗', 4900, '미용', 0, 'dogiman_facebrush.jpg', 3, '강아지', 'dogiman_facebrush_detail.jpg');
insert into product(product_no, product_name, product_price, product_category, product_qty, product_image, product_star_avg, product_pet_category, product_detail_image) values(product_product_no_SEQ.nextval, '도기맨 허니스마일 이중참빗', 6200, '미용', 0, 'dogiman_doublebrush.jpg', 4, '강아지', 'dogiman_doublebrush_detail.jpg');
insert into product(product_no, product_name, product_price, product_category, product_qty, product_image, product_star_avg, product_pet_category, product_detail_image) values(product_product_no_SEQ.nextval, '도기맨 허니스마일 손잡이 참빗 S', 7000, '미용', 0, 'dogiman_chambrush.jpg', 4, '강아지', 'dogiman_chambrush_detail.jpg');
insert into product(product_no, product_name, product_price, product_category, product_qty, product_image, product_star_avg, product_pet_category, product_detail_image) values(product_product_no_SEQ.nextval, '도기맨 허니스마일 슬리커브러쉬 M', 8100, '미용', 0, 'dogiman_slikerbrush.jpg', 4, '강아지', 'dogiman_slikerbrush_detail.jpg');

insert into product(product_no, product_name, product_price, product_category, product_qty, product_image, product_star_avg, product_pet_category, product_detail_image) values(product_product_no_SEQ.nextval, '펫라움 릴리프 샴푸 500ml', 21900, '미용', 0, 'petraum_relief_shampoo.jpg', 5, '강아지', 'petraum_relief_shampoo_detail.jpg');
insert into product(product_no, product_name, product_price, product_category, product_qty, product_image, product_star_avg, product_pet_category, product_detail_image) values(product_product_no_SEQ.nextval, '펫라움 퍼리 샴푸 500ml', 20900, '미용', 0, 'petraum_pery_shampoo.jpg', 2, '강아지', 'petraum_pery_shampoo_detail.jpg');
insert into product(product_no, product_name, product_price, product_category, product_qty, product_image, product_star_avg, product_pet_category, product_detail_image) values(product_product_no_SEQ.nextval, '펫라움 저자극 천연 세정제 퍼리 강아지샴푸 여행용 소용량 160ml', 15900, '미용', 0, 'petraum_prevent_matted_fur_shampoo.jpg', 5, '강아지', 'petraum_prevent_matted_fur_shampoo_detail.jpg');
insert into product(product_no, product_name, product_price, product_category, product_qty, product_image, product_star_avg, product_pet_category, product_detail_image) values(product_product_no_SEQ.nextval, '펫라움 릴리프 강아지워터리스샴푸 200ml 발세정제 버블형', 19000, '미용', 0, 'petraum_relief_waterless_shampoo.jpg', 5, '강아지', 'petraum_relief_waterless_shampoo_detail.jpg');
insert into product(product_no, product_name, product_price, product_category, product_qty, product_image, product_star_avg, product_pet_category, product_detail_image) values(product_product_no_SEQ.nextval, '펫라움 카밍키핑 강아지크림 50ml 보습 로션 발바닥밤', 9900, '미용', 0, 'petraum_calming.jpg', 5, '강아지', 'petraum_calming_detail.jpg');

insert into product(product_no, product_name, product_price, product_category, product_qty, product_image, product_star_avg, product_pet_category, product_detail_image) values(product_product_no_SEQ.nextval, '하이포닉 볼류마이징 샴푸 500ml', 32000, '미용', 0, 'hyponic_dogshampoo.jpg', 0, '강아지', 'hyponic_dogshampoo_detail.jpg');
insert into product(product_no, product_name, product_price, product_category, product_qty, product_image, product_star_avg, product_pet_category, product_detail_image) values(product_product_no_SEQ.nextval, '하이포닉 하얀 강아지용 샴푸 500ml', 32000, '미용', 0, 'hyponic_whitecoats_shampoo.jpg', 0, '강아지', 'hyponic_whitecoats_shampoo_detail.jpg');

insert into product(product_no, product_name, product_price, product_category, product_qty, product_image, product_star_avg, product_pet_category, product_detail_image) values(product_product_no_SEQ.nextval, '바른 고양이 두부모래 오리지널 7L', 12400, '모래', 0, 'bareunmorae_orange.jpg', 0, '고양이', 'bareunmorae_orange_detail.jpg');
insert into product(product_no, product_name, product_price, product_category, product_qty, product_image, product_star_avg, product_pet_category, product_detail_image) values(product_product_no_SEQ.nextval, '바른 두부모래 그린티 7L ', 12400, '모래', 0, 'bareunmorae_green.jpg', 0, '고양이', 'bareunmorae_green_detail.jpg');